### ISSUE TITLE
Run e2e tests on CI

### ISSUE THREAD

**Issue by vygandas** [cortip/isomera#106]
We also need to have e2e tests up and running for core features. They are not being run and are kept as they were created by default.
Include e2e in tests CI and make sure they pass successfully. It can be default tests, but should work ok.

### Acceptance criteria

- e2e tests run for every PR, but only for a modified app (api, platform, landing), not all every time
- necessary adjustments are made on implementation and tests to make it proper
- on api, user sign-up process covered with e2e tests (new)
- on api, user sign-in process covered with e2e tests (new)
- on platform, user sign-up process covered with e2e tests (new)
- on platform, user sign-in process covered with e2e tests (new)
- in `docs/`, there's a new document, `e2e-readme.md` created with explanations of how it works, what the developer needs to know, how to run it, how it is set up, etc. No need to expand in many details, but mention everything what might be useful to get started

**Comment by luigimorel** [comment]
hi @vygandas , 
is this a paid issue? i would like to help...
