### ISSUE TITLE
Database Naming Standards

### ISSUE THREAD

**Issue by llong2195** [cortip/isomera#133]
**Is your feature request related to a problem?** 
I want to introduce the rules for naming entities and columns
This helps everything look clearer
I can monitor the column without having to go into the database or migration file to see it

**Describe the solution you'd like**

     @Column({ name: 'user_id', type: 'int', unsigned: true, default: () => "'0'" })
     userId: number;`

     @Column({ name: 'user_name', type: 'varchar', nullable: true, length: 512 })
     userName: string;
We have to code and rewrite a lot more, but compared to the benefits it seems great :) 

**Describe alternatives you've considered** 
No ideas
**Additional context**

**Comment by vygandas** [comment]
@llong2195 great initiative :)
Let's figure this out: why do we need to mix camel and snake cases?
I mean, why this isn't ok 👇🏻 ?
```
 @Column({ name: 'userName', type: 'varchar', nullable: true, length: 512 })
 userName: string;
```

**Comment by llong2195** [comment]
@vygandas No problem, it seems I'm used to working with mix =))

**Comment by vygandas** [comment]
@llong2195 One more thing - since we do not use automatic sync and rely on migrations, we don't really need to put all these database column parameters. It won't generate types or won't do anything with the database itself. Unless I don't know something myself lol 😅

**Comment by llong2195** [comment]
@vygandas Just a few important parameters like `type`, `default`, `comment` or `name` if using `mix` like me

**Comment by llong2195** [comment]
@vygandas It's scary to use auto-sync on a production environment 🤣

**Comment by vygandas** [comment]
@llong2195 so many things could go wrong with auto 🤣 

![image](https://github.com/cortip/isomera/assets/723200/fea4a8de-a1d1-4a57-9dee-96417490ab04)
